Feature/intro
depromeet/9th_muyaho_android pull request #3
Opened 2021-04-07 17:16 UTC by mjjang88

1. 앱 진입 스플래시 화면 구현
2. 임시 HomeFragment 추가 (자동 생성됨)

2021-04-10 07:23 UTC, SongSieun requested changes

2021-04-10 07:23 UTC, SongSieun commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
얘는 어디서 쓰이는 걸까요?/

2021-04-10 07:23 UTC, SongSieun commented on app/src/main/java/com/depromeet/muyaho/LaunchSplashActivity.kt
> +class LaunchSplashActivity : AppCompatActivity() {
그냥 Splash로 해도 될것같은데 LaunchSplash 로 하신 이유가 있을까요?

2021-04-10 07:23 UTC, SongSieun commented on app/src/main/java/com/depromeet/muyaho/LaunchSplashActivity.kt
> +class LaunchSplashActivity : AppCompatActivity() {
BaseActivity, BaseFragment, BaseViewModel 만들어야할것 같은데 같이 논의 해봐야겠네염 ㅜㅜ..

2021-04-10 07:23 UTC, SongSieun commented on app/src/main/java/com/depromeet/muyaho/LaunchSplashActivity.kt
> +            delay(2000)
초기화 작업은 viewmodel 로 옮기는게 좋을것 같아요~

2021-04-10 07:23 UTC, SongSieun commented on app/src/main/java/com/depromeet/muyaho/MainActivity.kt
> +package com.depromeet.muyaho
main? home? 탭별로 패키지 나누는게 어떨까용?

2021-04-11 14:36 UTC, mjjang88 commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
auto import? 하다가 들어간 것 같은데, 사용되지 않는 것 같습니다.
삭제 처리했어요~

2021-04-11 14:38 UTC, mjjang88 commented on app/src/main/java/com/depromeet/muyaho/LaunchSplashActivity.kt
> +class LaunchSplashActivity : AppCompatActivity() {
좀 자세히 적어볼까 해서 작성했던 거고
저도 평소에 Splash라고 작성해서 Splash로 변경해 놓을게요

2021-04-11 14:53 UTC, mjjang88 commented on app/src/main/java/com/depromeet/muyaho/LaunchSplashActivity.kt
> +            delay(2000)
viewmodel의 function 콜은 액티비티에서 처리하지 않나요?
저는 저기에서 viewmodel.xxx() 와 같은 형태로 사용하는 걸로 생각하고 있었어요.

2021-04-11 14:56 UTC, mjjang88 commented on app/src/main/java/com/depromeet/muyaho/MainActivity.kt
> +package com.depromeet.muyaho
패키지 쪼개는 쪽으로 가는거 찬성입니다.

2021-04-12 09:00 UTC, SongSieun commented on app/src/main/java/com/depromeet/muyaho/LaunchSplashActivity.kt
> +            delay(2000)
viewmodel에 init{} 사용하면돼요!

2021-04-12 09:01 UTC, SongSieun commented on app/src/main/java/com/depromeet/muyaho/MainActivity.kt
> +package com.depromeet.muyaho
home 패키지로 분리 부탁드릴게용!

2021-04-13 13:46 UTC, mjjang88 commented on app/src/main/java/com/depromeet/muyaho/LaunchSplashActivity.kt
> +            delay(2000)
이해 했습니다.

2021-04-13 13:47 UTC, mjjang88 commented on app/src/main/java/com/depromeet/muyaho/MainActivity.kt
> +package com.depromeet.muyaho
저 MainActivity는 Single Activity 구조에 사용될 단 하나의 액티비티라서요.
메인 화면을 보여주는 대상은 아닙니당.

2021-04-13 13:50 UTC, SongSieun commented on app/src/main/java/com/depromeet/muyaho/MainActivity.kt
> +package com.depromeet.muyaho
아하 그렇겠네용

2021-04-13 14:49 UTC, merged